django_bookmarks/django_bookmarks/urls.py
import os.path
from django.conf.urls import *
from django.views.generic import TemplateView

from bookmarks.views import *
from django_bookmarks.feeds import *


from django.contrib import admin
admin.autodiscover()

site_media = os.path.join(
os.path.dirname(__file__), 'site_media'
)
feeds = {
    'recent': RecentBookmarks
}
urlpatterns = patterns ('',
    # Examples:
    # url(r'^$', 'django_bookmarks.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    #Friends
    (r'^friends/(\w+)/$', friends_page),
    (r'^friend/add/$', friend_add),
    (r'^friend/invite/$', friend_invite),
                
    #feeds
    #(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
    #                         {'feed_dict': feeds}),
                        
    # Browsing
    (r'^$', main_page),
    (r'^user/(\w+)/$', user_page),
    (r'^tag/([^\s]+)/$', tag_page),
    (r'^tag/$', tag_cloud_page),
    (r'^search/$',search_page),
    (r'^vote/$', bookmark_vote_page),
    (r'^popular/$', popular_page),
    (r'^bookmark/(\d+)/$', bookmark_page),
                        
    #comments
                        
    (r'^comments/', include('django.contrib.comments.urls')),
                        
    #Session Management
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
    { 'document_root': site_media}),
    (r'^register/$', register_page),
    (r'register/success/$', TemplateView.as_view(template_name='registration/register_success.html'),
    #{'template': 'registration/register_success.html'}
    ),
    
    #Ajax
    (r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
                        
    #Account management
    (r'^save/$', bookmark_save_page),

    url(r'^admin/', admin.site.urls),
              )
              

django_bookmarks/bookmarks/models.py
from django.db import models
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings

from django.contrib.auth.models import User

class Link(models.Model):
    url = models.URLField(unique=True)
    def __str__(self):
        return self.url
    class Admin:
        pass

class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)
    def __str__(self):
        return '%s, %s' %(self.user.username, self.link.url)
    def get_absolute_url(self):
        return self.link.url
    
    class Admin:
        list_display = ('title', 'link', 'user')
        list_filter = ('user',)
        ordering = ('title',)
        search_fields = ('title',)
    
class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)
    def __str__(self):
        return self.name
    class Admin:
        pass
    
class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)
    def __str__(self):
        return '%s, %s,' % self.bookmark, self.votes
    class Admin:
        pass
    
class Friendship(models.Model):
    from_friend = models.ForeignKey(
        User, related_name = 'friend_set'
    )
    to_friend = models.ForeignKey(
        User, related_name = 'to_friend_set'
    )
    def __str__(self):
        return '%s, %s' % (
            self.from_friend.username,
            self.to_friend.username
        )
    class Admin:
        pass
    class Meta:
        unique_together = (('to_friend', 'from_friend'),)
        
class Invitation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(User)
    def __str__(self):
        return '%s, %s' % (self.sender.username, self.email)
    def send(self):
        subject = 'Invitation to join Django Bookmarks'
        link = 'http://%s/friend/accept/%s/' % (
            settings.SITE_HOST,
            self.code
        )
        template = get_template('invitation_email.txt')
        context = Context({
            'name': self.name,
            'link': link,
            'sender': self.sender.username,
        })
        message = template.render(context)
        send_mail(
            subject,message,
            settings.DEFAULT_FROM_EMAIL, [self.email]
        )
    class Admin:
        pass

django_bookmarks/django_bookmarks/forms.py
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms
class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password Again',widget=forms.PasswordInput())
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Password do not match.')
        
    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')
        
class BookmarkSaveForm(forms.Form):
    url = forms.URLField(
        label = 'URL',
        widget = forms.TextInput(attrs={'size': 64})
    )
    title = forms.CharField(
        label = 'Title',
        widget = forms.TextInput(attrs={'size': 64})
    )
    tags = forms.CharField(
        label = 'Tags',
        required = False,
        widget = forms.TextInput(attrs={'size': 64})
    )
    share = forms.BooleanField(
        label = 'share on the main page',
        required = False
    )
    
class SearchForm(forms.Form):
    query = forms.CharField(
        label = 'Enter a keyword to search for',
        widget = forms.TextInput(attrs={'size': 32})
    )
    
class FriendInviteForm(forms.Form):
    name = forms.CharField(label='Friend\'s Name')
    email = forms.EmailField(label='Friend\'s Email')

django_bookmarks/django_bookmarks/templates/base.html
<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3c.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title>Django Bookmarks | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/site_media/style.css">
    <script type="text/javascript" src="/site_media/jquery.js"></script>
    {% block external %}{% endblock %}
    </head> 
    <body>
        <div id="nav">
        <a href="/">Home</a> |
            <a href="/popular/">popular bookmarks</a>|
            {% if user.is_authenticated %}
             {{ user.username }}
       
            <a href="/save/">add bookmark</a>|
            <a href="/search/">search</a>
            (<a href="/logout/">logout</a>)
            {% else %}
            <a href="/login/">login</a>|
            <a href="/register">register</a>
            {% endif %}
        </div>
    <h1>{% block head %} {% endblock %}</h1>
        
    {% block content %}{% endblock %}
        
    </body>

</html>

django_bookmarks/django_bookmarks/templates/bookmark_list.html
{% if bookmarks %}
<ul class="bookmarks">
 {% for bookmark in bookmarks %}
    <li>
    <a href="{{ bookmark.link.url }}" class="title">{{ bookmark.title | escape }}</a><br>
        {% if show_edit %}
        <a href="/save/?url={{ bookmark.link.url|urlencode}}" class="edit">[edit]</a><br>
        {% endif %}
        {% if show_tags %}
        Tags:
        {% if bookmark.tag_set.all %}
         <ul class="tags">
             {% for tag in bookmark.tag_set.all %}
             <li>
             <a href="/tag/{{tag.name}}/">{{ tag.name | escape }}</a>
             </li>
             {% endfor %}
        
        </ul>
        {% else %}
        None.
        {% endif %}<br>
        {% endif %}
        {% if show_user %}
        Posted by: 
        <a href="/user/{{ bookmark.user.username}}/" class="username">{{ bookmark.user.username }}</a>
        {% endif %}
    </li>
    {% endfor %}


</ul>
{% else %}
<p>No bookmarks found.</p>
{% endif %}

django_bookmarks/django_bookmarks/templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}
{% block title %} Bookmark: {{ shared_bookmark.bookmark.title|escape}} {% endblock %}
{% block head %}
  <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
  <a href="{{ shared_bookmark.bookmark.link.url}}" class="title">{{ shared_bookmark.bookmark.title|escape }}</a>
{% endblock %}
{% block content %}
Posted by:
<a href="/user/{{ shared_bookmark.bookmark.user.username}}/" class="username">{{ shared_bookmark.bookmark.user.username }}</a> |
<span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>

<h2>Comments</h2>
{% get_comment_count for bookmarks.sharedbookmark 
  shared_bookmark.id as comment_count %}

{% get_comment_list for bookmarks.sharedbookmark 
  shared_bookmark.is as comment_list %}

{% for comment in comment_list %}
<div class="comment">
    <p>
    <b>{{ comment.user.username }}</b> said:
    </p>
    {{comment.comment|escape|urlizetrunc:40|linebreaks }}


</div>
{% endfor %}
<p>Number of comments: {{ comment_count }} </p>
{% comment_form for bookmarks.sharedbookmark
shared_bookmark.id %}
{% endblock %}

django_bookmarks/django_bookmarks/templates/bookmark_save.html
{% extends "base.html" %}
{% block external %}

<link rel="stylesheet" href="/site_media/jquery.auto-complete.css" type="text/css">
<script type="text/javascript" src="/site_media/jquery.auto-complete.js"></script>
<script type="text/javascript" src="/site_media/jquery.auto-complete.min.js"></script>
<script type="text/javascript" src="/site_media/tag_autocomplete.js"></script>

{% endblock %}
{% block title %}Save Bookmarks {% endblock %}
{% block head %}Save Bookmarks {% endblock %}
{% block content %}

{% include 'bookmark_save_form.html' %}
{% endblock %}

django_bookmarks/django_bookmarks/templates/bookmark_save_form.html
<form id="save-form" method="post" action="/save/">
    {% csrf_token %}

    {{ form.as_p}}
    <input type="submit" value="save">

</form>

django_bookmarks/django_bookmarks/templates/friend_invite.html
{% extends "base.html" %}
{% block title %} Invite a friend {% endblock %}
{% block head %} Invite a friead {% endblock %}
{% block content %}

Enter your friend name and email below, and click "send invite" to invite your friend to join the site:
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="send invite">

</form>
{% endblock %}

django_bookmarks/django_bookmarks/templates/friends_page.html
{% extends "base.html" %}
{% block head %} Friends for {{ username }} {% endblock %}
{% block title %} Friends for {{ username }} {% endblock %}
{% block content %}

<h2>Friend List</h2>
{% if friends %}
<ul class="friends">
    {% for friend in friends %}
    <li><a href="/user/{{friend.username}}/">{{ friend.username }}</a></li>
    {% endfor %}

</ul>
{% else %}
<p>No friends found</p>
{% endif %}
<h2>Latest Friend Bookmarks</h2>
{% include 'bookmark_list.html' %}
{% endblock %}

django_bookmarks/django_bookmarks/templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block content %}
    {% if user.username %}
        <p>Welcome {{ user.username }}! Here you can store and share bookmarks!</p>
        {% else %}
        <p>Welcome anonymous user! You need to <a href="/login/">login</a> before you can store and share bookmarks</p>
        {% endif %}

<h2>Bookmark Shared by the Users</h2>
{% include 'shared_bookmark_list.html' %}
{% endblock %}
 

django_bookmarks/django_bookmarks/templates/popular_page.html
{% extends "base.html" %}
{% block title %} Popular Bookmarks {% endblock %}
{% block head %} Popular Bookmarks {% endblock %}
{% block content %} 

{% include 'shared_bookmark_list.html' %}

{% endblock %}

django_bookmarks/django_bookmarks/templates/search_page.html
{% extends "base.html" %}
{% block external %}
<script type="text/javascript" src="/site_media/search.js"></script>

{% endblock %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
{{ form.as_p }}
    <input type="submit" value="search">

</form>
<div id="search-results">
{% if show_results %}
    {% include 'bookmark_list.html' %}
    {% endif %}

</div>
{% endblock %}

django_bookmarks/django_bookmarks/templates/shared_bookmark_list.html
{% if shared_bookmarks %}
<ul class="bookmarks">
{% for shared_bookmark in shared_bookmarks %}
    <li>
        <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
    <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">{{ shared_bookmark.bookmark.title | escape}}</a> <br>
        Posted by:
        <a href="/user/{{ shared_bookmark.bookmark.user.username }}" class="username">
        {{ shared_bookmark.bookmark.user.username }}
        </a> | 
        <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
        <a href="/bookmark/{{ shared_bookmark.id}}">Comments</a>
    </li>
    {% endfor %}

</ul>
{% else %}
<p>No bookmarks found</p>
{% endif %}

django_bookmarks/django_bookmarks/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %} Tag Cloud {% endblock %}
{% block head %} Tag Cloud {% endblock %}
{% block content %}
<div id="tag-cloud">
{% for tag in tags %}
    <a href="/tag/{{ tag.name |escape}}/" class="tag-cloud-{{tag.weight}}">{{ tag.name |escape }}</a>
    {% endfor %}

</div>
{% endblock %}

django_bookmarks/django_bookmarks/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name |escape }} {% endblock %}
{% block head %}Bookmarks for tag : {{ tag_name | escape }} {% endblock %}
{% block content %}
  {% include "bookmark_list.html" %}
{% endblock %}

django_bookmarks/django_bookmarks/templates/user_page.html
{% extends "base.html" %}
{% block external %}

<script type="text/javascript" src="/site_media/bookmark_edit.js"></script>

{% endblock %}
{% block title %} {{ username }} {% endblock %}
{% block head %} Bookmarks for {{ username }} {% endblock %}
{% block content %}

{% ifequal user.username username %}
<a href="/friends/{{ username }}/">view your friends</a>
{% else %}
{% if is_friend %}
<a href="/friends/{{ user.username}}/">{{ username }} is a friend of yours</a>
{% else %}
<a href="/friend/add/?username={{ username }}">add {{ username }} to your friends</a>
{% endif %}
- <a href="/friends/{{ username }}/">view {{ username }}'s friends</a>
{% endifequal %}

{% include "bookmark_list.html" %}
{% endblock %}